### ISSUE TITLE
The generated path of Container Registry Credentials is wrong for add-on deployment

### ISSUE THREAD

**Issue by YingXue** [Azure/iot-edge-object-model#17]
**Describe the bug**
The path of Container Registry Credentials is wrong for add-on deployment

**To Reproduce**
1. Add a Container Registry Credentials for a new Add-on deployment
2. Go to Create and Review
3. Path shows as properties.desired.runtime.settings.registryCredentialsying.test1

**Expected behavior**
Path should be properties.desired.runtime.settings.registryCredentials.ying.test1

**Screenshots**

![image](https://user-images.githubusercontent.com/5489222/63809591-8b2cbe80-c8d7-11e9-8b6d-9b28438e4ca3.png)

**Comment by chieftn** [comment]
Thank you for the pr.  Superceded with pr addressing root cause of issue -- missing test case.
