### ISSUE TITLE
Type-o in EdgeAgentDesiredPropertiesViewModel

### ISSUE THREAD

**Issue by KamalAman** [Azure/iot-edge-object-model#30]
EdgeAgentDesiredPropertiesViewModel property `registryCredentials` is called `registyCredentials` with a missing `r` in https://github.com/Azure/iot-edge-object-model/blob/master/src/viewModel/%24EdgeAgentDesiredPropertiesViewModel.ts

**Comment by chieftn** [comment]
Thank you for the input.  We too noticed this just as we released version 3.0.  We'll incorporate a fix when we release v4.  The property name fortunately doesn't impact how registryCredentials are parsed or rendered to the underlying deployment manifest.

**Comment by chieftn** [comment]
This issue was corrected in version 4.0.0.  Thank you.
