### ISSUE TITLE
May we have a function to extract a deployment manifest from custom module twins

### ISSUE THREAD

**Issue by LanceLiMS** [Azure/iot-edge-object-model#38]
We got know that  we can use the following functions to extract a deployment manifest from system module twins.

const edgeModuleTwinsViewModel = {
    $edgeAgent: to$EdgeAgentModuleTwinViewModel(edgeAgentTwin),
    $edgeHub: to$EdgeHubModuleTwinViewModel(edgeHubTwin)
};

But for custom module, we can only find the push function:
![image](https://user-images.githubusercontent.com/77827376/118439731-20f62600-b719-11eb-8572-ce4d9777b995.png)

It would be really convenient if we have a function to do it, thanks in advance!

**Comment by chieftn** [comment]
Hi @LanceLiMS -- thank you for the inquiry.  Can you help me better understand your request?  The helper methods (to$EdgeAgentModuleTwinViewModel, etc) are intended to extract the manifest from module twins / configuration objects into an object model...and subsequently generate a manifest once changes to the object model have been applied.  Are you looking for greater convenience to manipulate the object model itself (e.g. short cut functions)?  

Thank you!

**Comment by chieftn** [comment]
Closing due to lack of response.
